In [2]:
import numpy as np
from mainHMM import *
#np.set_printoptions(formatter={'float': '{:.6f}'.format})

In [3]:
delta0 = Pi*B[:, O1[0]]
logdelta0 = np.log(Pi)+np.log(B[:, O1[0]])

In [4]:
delta_old2dcolwise = np.meshgrid(delta0, delta0)[1]
logdelta_old2dcolwise = np.meshgrid(logdelta0, logdelta0)[1]

In [5]:
logdelta_old2dcolwise_plus_A = logdelta_old2dcolwise + np.log(A)
delta_old2dcolwise_times_A = delta_old2dcolwise * A

In [6]:
delta_old2dcolwise_times_A.max(axis=0)

array([0.196  , 0.10803], dtype=float16)

In [7]:
np.e**logdelta_old2dcolwise_plus_A.max(axis=0)

array([0.1959 , 0.10785], dtype=float16)

In [8]:
np.log(delta_old2dcolwise_times_A.max(axis=0))

array([-1.63 , -2.225], dtype=float16)

In [9]:
logdelta_old2dcolwise_plus_A.max(axis=0)

array([-1.63 , -2.227], dtype=float16)

In [6]:
arnd = np.random.randint(-5,5,4)

In [7]:
amtrx = np.random.randint(-5,5,(4,4))

In [8]:
arnd * amtrx

array([[-16,   3,   0,   5],
       [  0,  -2,   0,  20],
       [  8,  -1,   0, -10],
       [-20,  -4,   0,   5]])

In [5]:
np.all([True,True,True])

True

In [2]:
Mx = np.array([[7,3],[4,6]])/10
My = np.array([[1,4,5],[7,2,1]])/10
p0 = np.array([6,4])/10

In [3]:
y_seq = np.array([0,1,0,2])#SMSL

In [4]:
def a(t=len(y_seq)-1):
    if t==0:
        return My[:,y_seq[0]]*p0
    return My[:,y_seq[t]]*(a(t-1) @ Mx)
def b(t):
    if t == len(y_seq)-1:
        return np.ones(len(p0))
    return Mx @ (My[:,y_seq[t+1]] * b(t+1))
def ab(t):
    return a(t) * b(t)
def g(t):
    abt = ab(t)
    return abt/(abt.sum())
def ab2d(t):
    at = a(t)
    bt = b(t+1)
    return Mx * ((My[:,y_seq[t+1]] * bt).reshape(len(bt),1) @ at.reshape(1,len(at))).T
def g2d(t):
    ab2dt = ab2d(t)
    return ab2dt/(ab2dt.sum())

In [5]:
gs = [g(i) for i in range(len(y_seq))]
abts = [ab(i).sum() for i in range(len(y_seq))]
abt2ds = [ab2d(i).sum() for i in range(len(y_seq)-1)]
a().sum()

0.009629599999999997

In [6]:
g(2)

array([0.22887763, 0.77112237])

In [7]:
g2d(2)

array([[0.21080834, 0.01806929],
       [0.59317106, 0.17795132]])

In [8]:
g2d(2).sum(axis=1)

array([0.22887763, 0.77112237])